"""Module to create an employee account"""
class Employee:
    SIZE = 0

    def __init__(self, name):
        """
        Create a new employee and autogenerate their id
        
        Args:
            name(str): Name of the new employee

        Return:
            None
        
        """
        self.name = name
        Employee.SIZE += 1
        base_id = "0000000"
        employee_count = str(Employee.SIZE)
        self._employee_id = base_id[len(employee_count):] + employee_count
        self.role = ""

    @property
    def employee_id(self):
        """
        Getter method for employee id

        Args:
            None

        Return:
            employee_id(str): Autogenerated id e.g "0000001"
        
        """
        return self._employee_id
    
    @employee_id.deleter
    def employee_id(self):
        """
        Remove employee id
        
        Args:
            None

        Return:
            None

        """
        del self._employee_id

    @property
    def start_date(self):
        return self._start_date
    
    @start_date.setter
    def start_date(self, start_date):
        """
        Set start date for the new employee
        
        Args:
            start_date(str): Date of employment commenced

        Return:
            None
        
        """
        self._start_date = start_date

    @start_date.deleter
    def start_date(self):
        del self._start_date

    
    @property
    def role(self):
        return self._role
    
    @role.setter
    def role(self, position):
        self._role = position

    @role.deleter
    def role(self):
        del self._role


    def __repr__(self):
        """
        Print the employee details
        
        Args:
            None

        Return:
            employee(Employee): Employee object with identifying details

        """
        return f"Name:\t\t{self.name}\nEmployee Id:\t{self.employee_id}\nRole:\t\t{self.role}\nEmployement Started:\t{self.start_date}"

