"""Module to create an employee account"""
class Employee:
    SIZE = 0

    def __init__(self, name):
        """Create a new employee and autogenerate their id
        
        Args:
            name(str): Name of the new employee

        Return:
            None
        
        """
        self.name = name
        Employee.SIZE += 1
        base_id = "0000000"
        employee_count = str(Employee.SIZE)
        self._employee_id = base_id[len(employee_count):] + employee_count

    @property
    def employee_id(self):
        """Getter method for employee id

        Args:
            None

        Return:
            employee_id(str): Autogenerated id e.g "0000001"
        
        """
        return self._employee_id
    
    @employee_id.setter
    def employee_id()

    @property
    def start_date(self):
        return self._start_date
    
    @start_date.setter
    def start_date(self, start_date):
        self._start_date = start_date

    @start_date.deleter
    def start_date(self):
        del self.start_date

